-- Aether MVP private persistence
-- The execution core owns only this schema. Public application tables are
-- intentionally excluded from this migration.

create schema if not exists aether_internal;

create table if not exists aether_internal.aether_v2_cases (
  case_id varchar(64) primary key,
  status varchar(64) not null,
  objective text not null,
  customer_type varchar(64) not null,
  owner_user_id varchar(128),
  tenant_id varchar(128),
  service_id varchar(128),
  updated_at timestamptz not null,
  payload jsonb not null
);

create index if not exists idx_aether_v2_cases_status
  on aether_internal.aether_v2_cases(status);
create index if not exists idx_aether_v2_cases_customer_type
  on aether_internal.aether_v2_cases(customer_type);
create index if not exists idx_aether_v2_cases_owner_user_id
  on aether_internal.aether_v2_cases(owner_user_id);
create index if not exists idx_aether_v2_cases_tenant_id
  on aether_internal.aether_v2_cases(tenant_id);
create index if not exists idx_aether_v2_cases_service_id
  on aether_internal.aether_v2_cases(service_id);

create table if not exists aether_internal.aether_v2_execution_events (
  id bigint generated by default as identity primary key,
  case_id varchar(64) not null,
  action varchar(128) not null,
  actor varchar(128) not null,
  tenant_id varchar(128),
  created_at timestamptz not null default now(),
  data jsonb not null default '{}'::jsonb
);

create index if not exists idx_aether_v2_events_case_id
  on aether_internal.aether_v2_execution_events(case_id);
create index if not exists idx_aether_v2_events_action
  on aether_internal.aether_v2_execution_events(action);
create index if not exists idx_aether_v2_events_tenant_id
  on aether_internal.aether_v2_execution_events(tenant_id);

create table if not exists aether_internal.aether_v2_task_queue (
  id bigint generated by default as identity primary key,
  case_id varchar(64) not null,
  task_id varchar(128) not null,
  status varchar(32) not null,
  available_at timestamptz not null,
  locked_by varchar(128),
  lease_until timestamptz,
  attempts integer not null default 0,
  last_error text,
  payload jsonb not null default '{}'::jsonb,
  constraint uq_aether_task_queue_case_task unique(case_id, task_id)
);

create index if not exists idx_aether_v2_queue_case_id
  on aether_internal.aether_v2_task_queue(case_id);
create index if not exists idx_aether_v2_queue_status
  on aether_internal.aether_v2_task_queue(status);
create index if not exists idx_aether_v2_queue_available_at
  on aether_internal.aether_v2_task_queue(available_at);
create index if not exists idx_aether_v2_queue_locked_by
  on aether_internal.aether_v2_task_queue(locked_by);
create index if not exists idx_aether_v2_queue_lease_until
  on aether_internal.aether_v2_task_queue(lease_until);

-- Keep these execution tables behind the private schema boundary.
alter table aether_internal.aether_v2_cases enable row level security;
alter table aether_internal.aether_v2_execution_events enable row level security;
alter table aether_internal.aether_v2_task_queue enable row level security;
