-- Aether MVP schema hardening for installations that already ran the first
-- private-persistence migration. This migration is idempotent and upgrades
-- existing V2 tables before enabling the production authorization boundary.

create schema if not exists aether_internal;

-- Existing installations may already have aether_v2_cases from the first MVP
-- migration with only the original columns.
alter table if exists aether_internal.aether_v2_cases
  add column if not exists owner_user_id varchar(128);
alter table if exists aether_internal.aether_v2_cases
  add column if not exists tenant_id varchar(128);
alter table if exists aether_internal.aether_v2_cases
  add column if not exists service_id varchar(128);

create index if not exists idx_aether_v2_cases_owner_user_id
  on aether_internal.aether_v2_cases(owner_user_id);
create index if not exists idx_aether_v2_cases_tenant_id
  on aether_internal.aether_v2_cases(tenant_id);
create index if not exists idx_aether_v2_cases_service_id
  on aether_internal.aether_v2_cases(service_id);

alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists tenant_id varchar(128);
alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists previous_hash varchar(128);
alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists event_hash varchar(128);
alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists sequence integer;

create index if not exists idx_aether_v2_events_tenant_id
  on aether_internal.aether_v2_execution_events(tenant_id);
create index if not exists idx_aether_v2_events_event_hash
  on aether_internal.aether_v2_execution_events(event_hash);

-- Unique only for assigned per-case sequence values. Existing legacy rows may
-- have NULL sequence and remain valid until new Aether writes use the field.
create unique index if not exists uq_aether_v2_events_case_sequence
  on aether_internal.aether_v2_execution_events(case_id, sequence);

create table if not exists aether_internal.aether_v2_task_queue (
  id bigint generated by default as identity primary key,
  case_id varchar(64) not null,
  task_id varchar(128) not null,
  status varchar(32) not null,
  available_at timestamptz not null,
  locked_by varchar(128),
  lease_until timestamptz,
  attempts integer not null default 0,
  last_error text,
  payload jsonb not null default '{}'::jsonb,
  constraint uq_aether_task_queue_case_task unique(case_id, task_id)
);
create index if not exists idx_aether_v2_queue_case_id
  on aether_internal.aether_v2_task_queue(case_id);
create index if not exists idx_aether_v2_queue_status
  on aether_internal.aether_v2_task_queue(status);
create index if not exists idx_aether_v2_queue_available_at
  on aether_internal.aether_v2_task_queue(available_at);
create index if not exists idx_aether_v2_queue_lease_until
  on aether_internal.aether_v2_task_queue(lease_until);

create table if not exists aether_internal.aether_v2_task_checkpoints (
  case_id varchar(64) not null,
  task_id varchar(128) not null,
  status varchar(32) not null,
  result jsonb,
  evidence jsonb not null default '[]'::jsonb,
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  attempts integer not null default 0,
  idempotency_key varchar(256),
  updated_at timestamptz not null default now(),
  primary key (case_id, task_id)
);

create table if not exists aether_internal.aether_v2_case_leases (
  case_id varchar(64) primary key,
  locked_by varchar(128) not null,
  lease_until timestamptz not null,
  heartbeat_at timestamptz not null
);

create index if not exists idx_aether_v2_case_leases_lease_until
  on aether_internal.aether_v2_case_leases(lease_until);

create table if not exists aether_internal.aether_v2_documents (
  document_id varchar(64) primary key,
  case_id varchar(64) not null,
  tenant_id varchar(128),
  owner_user_id varchar(128),
  document_type varchar(128) not null,
  filename varchar(512) not null,
  mime_type varchar(128) not null,
  size_bytes integer not null,
  sha256 varchar(128) not null,
  storage_key text not null,
  extracted_text text not null default '',
  extraction_mode varchar(64) not null default 'metadata-only',
  created_at timestamptz not null default now()
);

create table if not exists aether_internal.aether_v2_notifications (
  id bigint generated by default as identity primary key,
  tenant_id varchar(128),
  user_id varchar(128),
  case_id varchar(64),
  event_type varchar(128) not null,
  channel varchar(32) not null,
  destination varchar(512),
  status varchar(32) not null default 'queued',
  payload jsonb not null default '{}'::jsonb,
  idempotency_key varchar(256),
  attempts integer not null default 0,
  locked_by varchar(128),
  lease_until timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

alter table if exists aether_internal.aether_v2_notifications
  add column if not exists idempotency_key varchar(256);
alter table if exists aether_internal.aether_v2_notifications
  add column if not exists attempts integer not null default 0;
alter table if exists aether_internal.aether_v2_notifications
  add column if not exists locked_by varchar(128);
alter table if exists aether_internal.aether_v2_notifications
  add column if not exists lease_until timestamptz;
alter table if exists aether_internal.aether_v2_notifications
  add column if not exists last_error text;

create unique index if not exists uq_aether_v2_notifications_tenant_idempotency
  on aether_internal.aether_v2_notifications(tenant_id, idempotency_key);

create index if not exists idx_aether_v2_notifications_status
  on aether_internal.aether_v2_notifications(status);
create index if not exists idx_aether_v2_notifications_lease_until
  on aether_internal.aether_v2_notifications(lease_until);

create table if not exists aether_internal.aether_v2_payments (
  id bigint generated by default as identity primary key,
  payment_id varchar(64) unique not null,
  tenant_id varchar(128) not null,
  case_id varchar(64) not null,
  amount_minor integer not null,
  currency varchar(8) not null default 'INR',
  provider varchar(64) not null,
  provider_payment_id varchar(128),
  status varchar(32) not null,
  idempotency_key varchar(256) not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create unique index if not exists uq_aether_v2_payments_idempotency
  on aether_internal.aether_v2_payments(tenant_id, idempotency_key);

create table if not exists aether_internal.aether_v2_api_keys (
  id bigint generated by default as identity primary key,
  tenant_id varchar(128) not null,
  key_prefix varchar(32) unique not null,
  key_hash varchar(128) unique not null,
  role varchar(64) not null,
  scopes jsonb not null default '[]'::jsonb,
  status varchar(32) not null default 'active',
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  last_used_at timestamptz
);

create table if not exists aether_internal.aether_v2_usage (
  id bigint generated by default as identity primary key,
  tenant_id varchar(128) not null,
  case_id varchar(64),
  customer_type varchar(64),
  event_type varchar(64) not null,
  units integer not null default 1,
  unit_type varchar(32) not null default 'case',
  created_at timestamptz not null default now(),
  metadata_json jsonb not null default '{}'::jsonb,
  constraint uq_aether_usage_case_event unique(tenant_id, case_id, event_type)
);

-- Server-controlled membership registry.
create table if not exists public.aether_memberships (
  user_id uuid not null references auth.users(id) on delete cascade,
  tenant_id varchar(128) not null,
  role varchar(64) not null,
  status varchar(32) not null default 'active',
  department varchar(128),
  jurisdiction jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, tenant_id)
);
create index if not exists idx_aether_memberships_tenant
  on public.aether_memberships(tenant_id);
create index if not exists idx_aether_memberships_status
  on public.aether_memberships(status);

-- Production authorization boundary. Browser roles do not receive privileges
-- on the internal execution schema; the Render server uses the database
-- service connection for privileged reads/writes.
alter table aether_internal.aether_v2_cases enable row level security;
alter table aether_internal.aether_v2_execution_events enable row level security;
alter table aether_internal.aether_v2_task_queue enable row level security;
alter table aether_internal.aether_v2_task_checkpoints enable row level security;
alter table aether_internal.aether_v2_case_leases enable row level security;
alter table aether_internal.aether_v2_documents enable row level security;
alter table aether_internal.aether_v2_notifications enable row level security;
alter table aether_internal.aether_v2_payments enable row level security;
alter table aether_internal.aether_v2_api_keys enable row level security;
alter table aether_internal.aether_v2_usage enable row level security;

revoke all on schema aether_internal from anon, authenticated;
revoke all on all tables in schema aether_internal from anon, authenticated;

alter table public.aether_memberships enable row level security;
revoke all on public.aether_memberships from anon, authenticated;
grant select on public.aether_memberships to authenticated;

drop policy if exists "members can read their own membership" on public.aether_memberships;
create policy "members can read their own membership"
  on public.aether_memberships
  for select to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.handle_aether_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.aether_memberships (user_id, tenant_id, role, status)
  values (new.id, 'user:' || new.id::text, 'user', 'active')
  on conflict (user_id, tenant_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_aether_new_user() from public;
revoke all on function public.handle_aether_new_user() from anon, authenticated;

drop trigger if exists on_aether_auth_user_created on auth.users;
create trigger on_aether_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_aether_new_user();

-- Lock legacy public application tables until migrated behind the Aether API.
DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'citizens',
    'api_keys',
    'properties',
    'certificates',
    'workflow_states',
    'fraud_detection_logs',
    'trade_licenses',
    'building_permits',
    'water_connections',
    'birth_certificates',
    'death_certificates',
    'medical_licenses'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'DROP POLICY IF EXISTS "%s deny browser access" ON public.%I',
      table_name, table_name
    );
    EXECUTE format(
      'CREATE POLICY "%s deny browser access" ON public.%I
       FOR ALL TO anon, authenticated
       USING (false)
       WITH CHECK (false)',
      table_name, table_name
    );
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', table_name);
  END LOOP;
END
$$;
