-- Aether MVP private persistence
-- The execution core owns only this schema. Public application tables are
-- intentionally excluded from this migration.

create schema if not exists aether_internal;

create table if not exists aether_internal.aether_v2_cases (
  case_id varchar(64) primary key,
  status varchar(64) not null,
  objective text not null,
  customer_type varchar(64) not null,
  owner_user_id varchar(128),
  tenant_id varchar(128),
  service_id varchar(128),
  updated_at timestamptz not null,
  payload jsonb not null
);

create index if not exists idx_aether_v2_cases_status
  on aether_internal.aether_v2_cases(status);
create index if not exists idx_aether_v2_cases_customer_type
  on aether_internal.aether_v2_cases(customer_type);
create index if not exists idx_aether_v2_cases_owner_user_id
  on aether_internal.aether_v2_cases(owner_user_id);
create index if not exists idx_aether_v2_cases_tenant_id
  on aether_internal.aether_v2_cases(tenant_id);
create index if not exists idx_aether_v2_cases_service_id
  on aether_internal.aether_v2_cases(service_id);

create table if not exists aether_internal.aether_v2_execution_events (
  id bigint generated by default as identity primary key,
  case_id varchar(64) not null,
  action varchar(128) not null,
  actor varchar(128) not null,
  tenant_id varchar(128),
  created_at timestamptz not null default now(),
  data jsonb not null default '{}'::jsonb
);

create index if not exists idx_aether_v2_events_case_id
  on aether_internal.aether_v2_execution_events(case_id);
create index if not exists idx_aether_v2_events_action
  on aether_internal.aether_v2_execution_events(action);
create index if not exists idx_aether_v2_events_tenant_id
  on aether_internal.aether_v2_execution_events(tenant_id);

create table if not exists aether_internal.aether_v2_task_queue (
  id bigint generated by default as identity primary key,
  case_id varchar(64) not null,
  task_id varchar(128) not null,
  status varchar(32) not null,
  available_at timestamptz not null,
  locked_by varchar(128),
  lease_until timestamptz,
  attempts integer not null default 0,
  last_error text,
  payload jsonb not null default '{}'::jsonb,
  constraint uq_aether_task_queue_case_task unique(case_id, task_id)
);

create index if not exists idx_aether_v2_queue_case_id
  on aether_internal.aether_v2_task_queue(case_id);
create index if not exists idx_aether_v2_queue_status
  on aether_internal.aether_v2_task_queue(status);
create index if not exists idx_aether_v2_queue_available_at
  on aether_internal.aether_v2_task_queue(available_at);
create index if not exists idx_aether_v2_queue_locked_by
  on aether_internal.aether_v2_task_queue(locked_by);
create index if not exists idx_aether_v2_queue_lease_until
  on aether_internal.aether_v2_task_queue(lease_until);

create table if not exists aether_internal.aether_v2_task_checkpoints (
  case_id varchar(64) not null,
  task_id varchar(128) not null,
  status varchar(32) not null,
  result jsonb,
  evidence jsonb not null default '[]'::jsonb,
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  attempts integer not null default 0,
  idempotency_key varchar(256),
  updated_at timestamptz not null default now(),
  primary key (case_id, task_id)
);

create index if not exists idx_aether_v2_checkpoints_case_id
  on aether_internal.aether_v2_task_checkpoints(case_id);
create index if not exists idx_aether_v2_checkpoints_status
  on aether_internal.aether_v2_task_checkpoints(status);

-- Keep these execution tables behind the private schema boundary.
alter table aether_internal.aether_v2_cases enable row level security;
alter table aether_internal.aether_v2_execution_events enable row level security;
alter table aether_internal.aether_v2_task_queue enable row level security;
alter table aether_internal.aether_v2_task_checkpoints enable row level security;

-- The execution schema is never a browser/client data surface.
revoke all on schema aether_internal from anon, authenticated;
revoke all on all tables in schema aether_internal from anon, authenticated;


-- Server-controlled authorization membership registry.
create table if not exists public.aether_memberships (
  user_id uuid not null references auth.users(id) on delete cascade,
  tenant_id varchar(128) not null,
  role varchar(64) not null,
  status varchar(32) not null default 'active',
  department varchar(128),
  jurisdiction jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, tenant_id)
);

create index if not exists idx_aether_memberships_tenant
  on public.aether_memberships(tenant_id);
create index if not exists idx_aether_memberships_status
  on public.aether_memberships(status);

alter table public.aether_memberships enable row level security;

revoke all on public.aether_memberships from anon;
revoke all on public.aether_memberships from authenticated;
grant select on public.aether_memberships to authenticated;

create policy "members can read their own membership"
  on public.aether_memberships
  for select to authenticated
  using (user_id = (select auth.uid()));


create table if not exists aether_internal.aether_v2_usage (
  id bigint generated by default as identity primary key,
  tenant_id varchar(128) not null,
  case_id varchar(64),
  customer_type varchar(64),
  event_type varchar(64) not null,
  units integer not null default 1,
  unit_type varchar(32) not null default 'case',
  created_at timestamptz not null default now(),
  metadata_json jsonb not null default '{}'::jsonb,
  constraint uq_aether_usage_case_event unique(tenant_id, case_id, event_type)
);

create index if not exists idx_aether_v2_usage_tenant
  on aether_internal.aether_v2_usage(tenant_id);
create index if not exists idx_aether_v2_usage_event
  on aether_internal.aether_v2_usage(event_type);
create index if not exists idx_aether_v2_usage_case
  on aether_internal.aether_v2_usage(case_id);

alter table aether_internal.aether_v2_usage enable row level security;
revoke all on aether_internal.aether_v2_usage from anon, authenticated;


-- Tamper-evident event chain fields for existing V2 event tables.
alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists previous_hash varchar(128);

alter table if exists aether_internal.aether_v2_execution_events
  add column if not exists event_hash varchar(128);

create index if not exists idx_aether_v2_events_event_hash
  on aether_internal.aether_v2_execution_events(event_hash);


-- Provision a least-privilege Aether user membership when a new Auth user is
-- created. Elevated roles must still be assigned by an administrator.
create or replace function public.handle_aether_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.aether_memberships (user_id, tenant_id, role, status)
  values (new.id, 'user:' || new.id::text, 'user', 'active')
  on conflict (user_id, tenant_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_aether_new_user() from public;
revoke all on function public.handle_aether_new_user() from anon, authenticated;

drop trigger if exists on_aether_auth_user_created on auth.users;
create trigger on_aether_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_aether_new_user();
